In [4]:
import numpy as np
from numpy.linalg import inv, qr

In [7]:
X = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
X

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
X.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [10]:
X.T.dot(X)

array([[ 66,  78,  90],
       [ 78,  93, 108],
       [ 90, 108, 126]])

In [12]:
X. dot (X.T)

array([[ 14,  32,  50],
       [ 32,  77, 122],
       [ 50, 122, 194]])