In [1]:
# 수치 계산을 위한 NumPy와 선형대수 함수(inv: 역행렬, qr: QR 분해)를 불러옵니다.
# 이 노트북에서는 np를 사용하며, inv와 qr은 이후 선형대수 실습에 활용할 수 있습니다.
import numpy as np
from numpy.linalg import inv, qr

In [2]:
# 1부터 9까지의 값을 이용해 3행 3열 NumPy 배열 X를 생성합니다.
# 마지막 줄에 변수명 X를 적어 생성된 행렬의 형태와 값을 출력합니다.
X = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
X

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [3]:
# X.T는 행과 열을 서로 바꾼 전치행렬(transpose)을 반환합니다.
# 따라서 X의 첫 번째 열 [1, 4, 7]이 결과의 첫 번째 행이 됩니다.
X.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [4]:
# X의 전치행렬과 원래 행렬을 곱해 XᵀX를 계산합니다.
# 결과의 각 원소는 X의 두 열 벡터 사이의 내적이며, 3행 3열 대칭행렬이 됩니다.
X.T.dot(X)

array([[ 66,  78,  90],
       [ 78,  93, 108],
       [ 90, 108, 126]])

In [5]:
# 원래 행렬과 X의 전치행렬을 곱해 XXᵀ를 계산합니다.
# 결과의 각 원소는 X의 두 행 벡터 사이의 내적이며, XᵀX와 값은 다르지만 역시 대칭행렬입니다.
X. dot (X.T)

array([[ 14,  32,  50],
       [ 32,  77, 122],
       [ 50, 122, 194]])

In [ ]:
# 추가 NumPy 선형대수 연산을 자유롭게 실습하기 위한 빈 셀입니다.